---
title: "About"
author: "Amal Abdi"
date: "10/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidycensus)
library(tidyverse)

```

# About

This data is from the US census and the American community survey which is administered by the US government. The census is administered every 10 years. Every household is expected to fill out the survey. Meanwhile, the American Community Survey is conducted every year and is only based on a survey of 3 million households.

# About the data

Tidycensus is an R package that allows users to interface with the US Census Bureau’s decennial Census and five-year American Community APIs and return tidyverse-ready data frames, optionally with simple feature geometry included. Therefore, it stores two datasets that I will draw on for my final projects. Using the tidycensus package requeries installing an api key. Instructions can be found here: https://walkerke.github.io/tidycensus/articles/basic-usage.html. 
All the data is clean because it is already in an R package.

Because I used the following code and specified install = TRUE for the api key, I no longer have to run this.
  census_api_key("cec2ddb404f16f9748db315e2b03a90533b3f9a2", install = TRUE)


